const test = require('node:test');
const assert = require('node:assert/strict');
const os = require('node:os');
const path = require('node:path');
const fs = require('node:fs');
const { Store, PERMISSIONS, hashPassword, verifyPassword } = require('../lib/store');

test('passwords are salted and verified', () => { const hash = hashPassword('correct horse'); assert.notEqual(hash, 'correct horse'); assert.equal(verifyPassword('correct horse', hash), true); assert.equal(verifyPassword('wrong', hash), false); });
test('first user is administrator and subsequent users are not', () => { const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'resourcer-')); const store = new Store(path.join(dir, 'data.json')); const first = store.createUser({ username: 'Admin', password: 'password1', displayName: 'Admin User' }); const second = store.createUser({ username: 'person', password: 'password2', displayName: 'Team Person' }); assert.deepEqual(first.permissions, PERMISSIONS); assert.deepEqual(second.permissions, []); assert.equal(store.authenticate('admin', 'password1').id, first.id); });
test('teams, tasks and holidays persist', () => { const file = path.join(fs.mkdtempSync(path.join(os.tmpdir(), 'resourcer-')), 'data.json'); const store = new Store(file); store.addTeam({ name: 'Design', members: [] }); store.addTask({ title: 'Workshop', userId: '1' }); store.addHoliday({ note: 'Leave', userId: '1' }); const restored = new Store(file); assert.equal(restored.data.teams[0].name, 'Design'); assert.equal(restored.data.tasks[0].title, 'Workshop'); assert.equal(restored.data.holidays[0].note, 'Leave'); });
test('resources, teams, tasks and holidays can be edited and removed', () => { const file = path.join(fs.mkdtempSync(path.join(os.tmpdir(), 'resourcer-')), 'data.json'); const store = new Store(file); const user = store.createUser({ username: 'alex', password: 'password1', displayName: 'Alex' }); const team = store.addTeam({ name: 'Old team' }); const task = store.addTask({ title: 'Old task', userId: user.id }); const holiday = store.addHoliday({ note: 'Leave', userId: user.id }); assert.equal(store.updateUser(user.id, { displayName: 'Alex Morgan', email: 'a@example.com' }).displayName, 'Alex Morgan'); assert.deepEqual(store.updateTeam(team.id, { name: 'Design', description: 'Creative work', members: [{ userId: user.id }] }).members, [{ userId: user.id }]); assert.equal(store.updateTask(task.id, { title: 'Planning' }).title, 'Planning'); assert.equal(store.updateHoliday(holiday.id, { note: 'Summer break' }).note, 'Summer break'); store.removeTask(task.id); store.removeHoliday(holiday.id); assert.equal(store.data.tasks.length, 0); assert.equal(store.data.holidays.length, 0); });
